model_name: "Watson" # Lestrade, Watson, Sherlock, Polimi

path_model_watson: "./detective/checkpoints/checkpoint_watson.pt"
path_model_sherlock: "./detective/checkpoints/checkpoint_sherlock.pt"

train_path: "./data/train"
val_path: "./data/val"
test_path: "./data/test"
test_adv_path: "./data/test_adv"
eval_res_path: "./eval_results"

test_adv_bool: True

seed: 1234
batch_size: 8
learning_rate: 0.001
epochs_training: 20
epochs_adversarial_training: 20
early_stopping_patience: 3

adversarial_attack_type: "FGSM" # LinfPGD, PGD, FGSM
