model_name: "Sherlock" # Watson, Polimi

path_model_watson: "./detective/checkpoints/checkpoint_watson.pt"
path_model_sherlock: "./detective/checkpoints/checkpoint_sherlock.pt"

train_path: "./data/train"
val_path: "./data/val"
test_path: "./data/test"

seed: 1234
batch_size: 8
learning_rate: 0.001
epochs_adversarial_training: 20
early_stopping_patience: 3
